// File generated by FlutterFire CLI. // ← FlutterFire CLI によって自動生成されたファイル
// ignore_for_file: type=lint // ← Lint（静的解析）警告を無視する指定

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions; // ← Firebase の初期化に必要な FirebaseOptions クラスをインポート
import 'package:flutter/foundation.dart' // ← Flutter の基盤ライブラリをインポート
    show defaultTargetPlatform, kIsWeb, TargetPlatform; // ← 現在の実行プラットフォームを判定するために使用

/// Default [FirebaseOptions] for use with your Firebase apps. // ← Firebase アプリ設定のデフォルトオプション定義を示すドキュメントコメント
///
/// Example: // ← 使用例の説明
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions { // ← Firebase 各プラットフォームの設定情報を保持するクラス
  static FirebaseOptions get currentPlatform { // ← 現在の実行環境に応じた Firebase 設定を返すゲッター
    if (kIsWeb) { // ← Web 実行時は未設定のためエラーを投げる
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - ' // エラーメッセージ（Webは未対応）
            'you can reconfigure this by running the FlutterFire CLI again.', // FlutterFire CLIを再実行して設定可能
      );
    }
    switch (defaultTargetPlatform) { // ← 実行プラットフォームごとの分岐処理
      case TargetPlatform.android: // ← Android の場合
        return android; // Android用設定を返す
      case TargetPlatform.iOS: // ← iOS の場合
        return ios; // iOS用設定を返す
      case TargetPlatform.macOS: // ← macOS の場合
        throw UnsupportedError( // macOS未対応のためエラーをスロー
          'DefaultFirebaseOptions have not been configured for macos - ' // エラーメッセージ
              'you can reconfigure this by running the FlutterFire CLI again.', // FlutterFire CLIで再設定可能
        );
      case TargetPlatform.windows: // ← Windows の場合
        throw UnsupportedError( // Windowsも未対応
          'DefaultFirebaseOptions have not been configured for windows - ' // エラーメッセージ
              'you can reconfigure this by running the FlutterFire CLI again.', // 再設定案内
        );
      case TargetPlatform.linux: // ← Linux の場合
        throw UnsupportedError( // Linuxも未対応
          'DefaultFirebaseOptions have not been configured for linux - ' // エラーメッセージ
              'you can reconfigure this by running the FlutterFire CLI again.', // 再設定案内
        );
      default: // ← その他のプラットフォーム（想定外）
        throw UnsupportedError( // どの環境にも当てはまらない場合のエラー
          'DefaultFirebaseOptions are not supported for this platform.', // 未対応プラットフォームのエラー
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions( // ← Android 用の Firebase 設定を定義
    apiKey: 'FIREBASE_ANDROID_API_KEY', // ← Firebase プロジェクトのAPIキー
    appId: '1:281104655266:android:087ada22f30aeaa07748fb', // ← FirebaseアプリのID
    messagingSenderId: '281104655266', // ← Firebase Cloud Messagingの送信者ID
    projectId: 'api-app-cc4de', // ← FirebaseプロジェクトID
    storageBucket: 'api-app-cc4de.firebasestorage.app', // ← Firebase StorageのURL
  );

  static const FirebaseOptions ios = FirebaseOptions( // ← iOS 用の Firebase 設定を定義
    apiKey: 'FIREBASE_IOS_API_KEY', // ← FirebaseプロジェクトのAPIキー（iOS用）
    appId: '1:281104655266:ios:c6da651f1478150e7748fb', // ← FirebaseアプリのID（iOS）
    messagingSenderId: '281104655266', // ← Firebase Cloud Messagingの送信者ID
    projectId: 'api-app-cc4de', // ← FirebaseプロジェクトID
    storageBucket: 'api-app-cc4de.firebasestorage.app', // ← Firebase StorageのURL
    iosBundleId: 'com.example.googlemapApi', // ← iOSアプリのバンドルID
  );
}

// =============================
// 🧩 このファイル全体の説明
// =============================
// このファイルは、FlutterFire CLI によって自動生成された Firebase 設定ファイル。
// 各プラットフォーム（Android / iOS）に対応する FirebaseOptions を定義し、
// アプリ起動時に `Firebase.initializeApp()` へ渡すために使用される。
//
// 【主な役割】
// ・Android / iOS 環境ごとの Firebase APIキー、アプリID、プロジェクトIDを管理。
// ・実行中のプラットフォームを自動判定し、適切な設定を返す（`currentPlatform`）。
// ・Web, macOS, Windows, Linux など未設定環境では明示的にエラーを出す。
//
// このファイルは基本的に手動編集不要で、Firebaseプロジェクト設定変更時は
// FlutterFire CLI の `flutterfire configure` コマンドで再生成する。
